language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.4
  - nightly
after_success:
  - julia -e 'cd(Pkg.dir("JsonBuilder")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
